export const DEFAULT_ITEMS = [
    "Things that don't sound as bad when you sing them",
    "If Tennis commentators were brutally honest",
    "Rejected slogans for the Australian Open",
    "Inappropriate times to crack open a beer ",
    "Unlikely things to hear in a Trump speech",
    "Unlikely New Year’s resolutions",
    "Things your shouldn't say just after a kiss",
    "NYE actually stands for (make up a funny version)",
    "Strange things to hear your GPS say",
    "Unlikely tag lines for a dating app",
    "Things overheard during Dry January",
    "Things you wish you could say to the Melbourne Comedy Festival Director",
    "Strange ways to celebrate the New Year",
    "Weird items sold on Facebook Marketplace",
    "Audience choice (•‿•)",
    "Bad things to say while getting arrested",
    "Bad pickup lines",
    "Which is the best suburb in Melbourne and why?",
    "If your life were a cocktail, what would it be called, and what are the ingredients?",
    "My eulogy will probably go something like...",
    "Strange things to read on road signs while you're driving",
    "Things TikTok would say about being banned in the US",
    "Things you don’t want to hear from your Pilot",
    "Strange rumours about the Melbourne comedy scene",
    "Unlikely quotes from historical figures",
    "Unusual times to use the phrase \"Tada\"",
    "Last time I was heckled...",
    "Rejected Standup comedy special titles",
    "If you met Donald Trump, what would you say to him?",
    "Celebrities that shouldn't have been famous"
];